(()=>{'use strict';
const S={p:'dc_products_v3',d:'dc_days_v3',a:'delite_cravings_auth_v2'},$=id=>document.getElementById(id);
const D=[["DC-001","Snacks","Meat Pie",0,0],["DC-002","Snacks","Chicken Pie",0,0],["DC-003","Snacks","Sausage",0,0],["DC-004","Snacks","Hotdog",0,0],["DC-005","Snacks","Coconut",0,0],["DC-006","Snacks","Pineapple",0,0],["DC-007","Snacks","Doughnut",0,0],["DC-008","Snacks","Fish Roll",0,0],["DC-009","Snacks","Egg Roll",0,0],["DC-010","Snacks","Buns",0,0],["DC-011","Snacks","Fish Pie",0,0],["DC-012","Snacks","Puff Puff",0,0],["DC-013","Snacks","Cupcakes",0,0],["DC-014","Snacks","Akara's",0,0],["DC-015","Snacks","Plantain Chips",0,0],["DC-016","Bread","Bread 2,000",2000,0],["DC-017","Bread","Bread 1,500",1500,0],["DC-018","Bread","Bread 800",800,0],["DC-019","Bread","Bread 500",500,0],["DC-020","Drinks","Cola",0,0],["DC-021","Drinks","Pepsi",0,0],["DC-022","Drinks","Fayrouz",0,0],["DC-023","Drinks","Malt Can",0,0],["DC-024","Drinks","Viju Barbed",0,0],["DC-025","Drinks","Viju Wheat",0,0],["DC-026","Drinks","Viju Choco",0,0],["DC-027","Drinks","American Cola",0,0],["DC-028","Drinks","Nutri Choco",0,0],["DC-029","Drinks","Maca",0,0],["DC-030","Drinks","Fearless",0,0],["DC-031","Drinks","Commando",0,0],["DC-032","Drinks","Predator",0,0],["DC-033","Drinks","Big Soss",0,0],["DC-034","Drinks","Big Pally",0,0],["DC-035","Drinks","Lucozade Boost",0,0],["DC-036","Drinks","35cl Pet Malt",0,0],["DC-037","Drinks","50cl Pet Malt",0,0],["DC-038","Drinks","Eva Water",0,0],["DC-039","Drinks","Bottle Water",0,0],["DC-040","Drinks","Dudu Yog",0,0],["DC-041","Drinks","Dudu Red",0,0],["DC-042","Drinks","Nutri Milk",0,0],["DC-043","Drinks","U Milk",0,0],["DC-044","Drinks","Viju Yog",0,0],["DC-045","Drinks","Reach",0,0],["DC-046","Drinks","Dudu Mixed",0,0],["DC-047","Drinks","Nutri Fox Active",0,0],["DC-048","Drinks","Small Mineral",0,0],["DC-049","Drinks","Big Pocari",0,0],["DC-050","Drinks","Small Pocari",0,0],["DC-051","Drinks","50cl Cedar",0,0],["DC-052","Drinks","35cl Cedar",0,0],["DC-053","Drinks","Small Sosh",0,0],["DC-054","Drinks","Gball",0,0],["DC-055","Drinks","Vitamilk",0,0],["DC-056","Drinks","Hollandais",0,0],["DC-057","Drinks","Chivita",0,0],["DC-058","Drinks","Desperado",0,0],["DC-059","Drinks","Trophy",0,0],["DC-060","Drinks","Origin",0,0],["DC-061","Drinks","Red Bull",0,0],["DC-062","Drinks","Monster",0,0],["DC-063","Drinks","Smirnoff",0,0],["DC-064","Drinks","Budweiser",0,0],["DC-065","Drinks","Can Cola",0,0],["DC-066","Drinks","Can Schweppes",0,0],["DC-067","Drinks","Umas",0,0],["DC-068","Drinks","Tropical Big",0,0],["DC-069","Drinks","Berry Blast",0,0],["DC-070","Drinks","Mango Burst",0,0],["DC-071","Drinks","Pet Schweppes",0,0],["DC-072","Drinks","Mona Cola",0,0],["DC-073","Drinks","Mr Cream",0,0],["DC-074","Drinks","Slow Sip",0,0],["DC-075","Drinks","Maccaws",0,0],["DC-076","Drinks","Fresh Up",0,0]].map(x=>({id:x[0],category:x[1],name:x[2],price:x[3],opening:x[4]}));
const read=(k,f)=>{try{let x=localStorage.getItem(k);return x===null?f:JSON.parse(x)}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){console.error('Save failed',e);return false}},num=x=>Math.max(0,Number(x)||0),today=()=>new Date().toLocaleDateString('en-CA'),money=x=>'₦'+Number(x||0).toLocaleString('en-NG',{maximumFractionDigits:2}),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=read(S.p,null); if(!Array.isArray(products)) products=read('dc_products_v2',null); if(!Array.isArray(products)) products=[]; let days=read(S.d,{});
if(!days||typeof days!=='object'||Array.isArray(days))days={};
const existingNames=new Set(products.map(x=>String(x.name||'').trim().toLowerCase()));
D.forEach(p=>{if(!existingNames.has(p.name.toLowerCase())){products.push({...p});existingNames.add(p.name.toLowerCase())}});
write(S.p,products);write(S.d,days);
const calc=r=>{let available=num(r.opening)+num(r.added),closing=Math.min(num(r.closing),available),sold=available-closing;return{available,closing,sold,sales:sold*num(r.price)}};
const auth=()=>{let a=read(S.a,{username:'admin',pin:'1234'});return a?.username&&a?.pin?a:{username:'admin',pin:'1234'}};
const prev=d=>{let x=new Date(d+'T12:00:00');x.setDate(x.getDate()-1);return x.toLocaleDateString('en-CA')};
const openStock=(p,d)=>{let old=days[d]?.rows?.find(x=>x.id===p.id);if(old)return num(old.opening);let pr=days[prev(d)]?.rows?.find(x=>x.id===p.id);return pr?calc(pr).closing:num(p.opening)};
let rows=[];
const UI='dc_ui_state_v1',ui=(()=>{try{return JSON.parse(sessionStorage.getItem(UI))||{}}catch{return{}}})(),saveUI=()=>{try{sessionStorage.setItem(UI,JSON.stringify(ui))}catch{}};
let saveTimer=null,dirty={d:false,p:false};
function status(m,state){let s=$('saveStatus');if(s){s.textContent=m;s.dataset.state=state}}
function flush(){clearTimeout(saveTimer);saveTimer=null;if(!dirty.d&&!dirty.p)return true;let ok=true;if(dirty.d){if(write(S.d,days))dirty.d=false;else ok=false}if(dirty.p){if(write(S.p,products))dirty.p=false;else ok=false}status(ok?'All changes saved':'Save failed — storage full',ok?'saved':'error');if(!ok)toast('Could not save. Free up browser storage.');return ok}
function schedule(){status('Saving…','saving');clearTimeout(saveTimer);saveTimer=setTimeout(flush,300)}
function persistDay(){let d=$('businessDate').value||today();days[d]={...(days[d]||{}),date:d,updatedAt:new Date().toISOString(),rows:rows.map(r=>({...r}))};dirty.d=true;schedule()}
function persistProducts(){dirty.p=true;schedule()}
function toast(m){let x=$('toast');x.textContent=m;x.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove('show'),2000)}
function totals(rs){let t={sales:0,units:0,added:0,closing:0,p:{},c:{}};rs.forEach(r=>{let z=calc(r);t.sales+=z.sales;t.units+=z.sold;t.added+=num(r.added);t.closing+=z.closing;t.p[r.name]=(t.p[r.name]||0)+z.sales;t.c[r.category]=(t.c[r.category]||0)+z.sales});return t}
function tab(n){if(!$(n))n='sales';flush();ui.tab=n;saveUI();document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===n));document.querySelectorAll('.tab-section').forEach(x=>x.classList.toggle('active',x.id===n));if(n==='sales')sales();if(n==='products')prod();if(n==='reports')reports();if(n==='analytics')analytics()}
function sales(){let d=$('businessDate').value||today(),saved=days[d]?.rows||[];rows=products.map(p=>{let o=saved.find(x=>x.id===p.id),opening=o?num(o.opening):openStock(p,d);return{id:p.id,category:p.category,name:p.name,price:num(o?.price??p.price),opening,added:num(o?.added),closing:o?num(o.closing):opening}});let q=($('salesSearch').value||'').toLowerCase(),v=rows.filter(r=>(r.name+' '+r.category+' '+r.id).toLowerCase().includes(q));$('salesBody').innerHTML=v.map(r=>{let z=calc(r);return '<tr data-id="'+esc(r.id)+'"><td>'+esc(r.category)+'</td><td><b>'+esc(r.name)+'</b><small class="muted"> '+esc(r.id)+'</small></td><td><input data-f="opening" type="number" min="0" value="'+r.opening+'"></td><td><input data-f="added" type="number" min="0" value="'+r.added+'"></td><td class="av">'+z.available+'</td><td><input data-f="closing" type="number" min="0" max="'+z.available+'" value="'+z.closing+'"></td><td class="sold"><input data-f="sold" type="number" min="0" max="'+z.available+'" value="'+z.sold+'" aria-label="Units sold for '+esc(r.name)+'"></td><td><div class="add-sale"><input class="add-qty" type="number" min="1" placeholder="Qty" aria-label="Add units sold for '+esc(r.name)+'"><button class="btn add-sale-btn" type="button">Add</button></div></td><td><input data-f="price" type="number" min="0" value="'+r.price+'"></td><td class="rev"><b>'+money(z.sales)+'</b></td></tr>'}).join('')||'<tr><td colspan="10" class="muted">No products found.</td></tr>';summary();saveLabel()}
function saveLabel(){let d=$('businessDate').value||today();$('saveDayBtn').textContent=days[d]?.savedAt?'Update Day':'Save Day'}
function refreshRow(tr,r,active){let z=calc(r);r.closing=z.closing;tr.querySelector('.av').textContent=z.available;tr.querySelector('.rev b').textContent=money(z.sales);let c=tr.querySelector('[data-f="closing"]'),s=tr.querySelector('[data-f="sold"]');c.max=z.available;s.max=z.available;if(c!==active||num(c.value)>z.available)c.value=z.closing;if(s!==active||num(s.value)>z.available)s.value=z.sold}
function addSale(tr){let q=tr.querySelector('.add-qty'),n=Math.floor(num(q.value)),r=rows.find(x=>x.id===tr.dataset.id);if(!r||!n){q.focus();return}let z=calc(r);if(n>z.closing){toast('Only '+z.closing+' '+r.name+' left in stock');return}r.closing=z.closing-n;q.value='';refreshRow(tr,r);summary();persistDay();toast('Added '+n+' sold: '+r.name)}
function moveDay(from,to){if(!from||!to||from===to)return false;flush();let src=days[from];if(!src){toast('Nothing recorded on '+from+' yet');return false}if(days[to]&&!confirm('A report already exists for '+to+'. Replace it?'))return false;days[to]={...src,date:to,updatedAt:new Date().toISOString()};delete days[from];dirty.d=true;if(!flush())return false;$('businessDate').value=to;ui.date=to;saveUI();sales();reports();analytics();toast('Report moved to '+to);return true}
function openMove(from){if(!days[from]){toast('Nothing recorded on '+from+' yet');return}$('moveDialog').dataset.from=from;$('moveFrom').textContent='Current date: '+from;$('moveTo').value=from;$('moveDialog').showModal();$('moveTo').focus()}
function summary(){let t=totals(rows);$('mSales').textContent=money(t.sales);$('mUnits').textContent=t.units;$('mAdded').textContent=t.added;$('mClosing').textContent=t.closing;$('categorySummary').innerHTML=Object.entries(t.c).map(([k,v])=>'<div class="category-card"><span class="muted">'+esc(k)+'</span><strong>'+money(v)+'</strong><small>'+rows.filter(r=>r.category===k).reduce((n,r)=>n+calc(r).sold,0)+' units sold</small></div>').join('')}
function productsUI(){let p=products;$('productsBody').innerHTML=p.map(x=>'<tr data-pid="'+esc(x.id)+'"><td><select data-f="category"><option '+(x.category==='Drinks'?'selected':'')+'>Drinks</option><option '+(x.category==='Snacks'?'selected':'')+'>Snacks</option><option '+(x.category==='Bread'?'selected':'')+'>Bread</option></select></td><td><input data-f="name" value="'+esc(x.name)+'"></td><td>'+esc(x.id)+'</td><td><input data-f="price" type="number" min="0" value="'+num(x.price)+'"></td><td><input data-f="opening" type="number" min="0" value="'+num(x.opening)+'"></td><td><button class="btn btn-danger rm" type="button">Remove</button></td></tr>').join('')}
function prod(){productsUI()}
function dateList(a,b){let out=[];if(!a||!b||a>b)return out;let d=new Date(a+'T12:00:00'),e=new Date(b+'T12:00:00');while(d<=e){out.push(d.toLocaleDateString('en-CA'));d.setDate(d.getDate()+1)}return out}
function reports(){let ds=Object.values(days).filter(d=>d&&d.date).sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('reportsBody').innerHTML=ds.map(d=>{let t=totals(d.rows||[]);return '<tr><td>'+d.date+'</td><td>'+money(t.sales)+'</td><td>'+t.units+'</td><td>'+t.added+'</td><td>'+t.closing+'</td><td><div class="reports-actions"><button class="btn open" data-date="'+d.date+'" type="button">Edit</button><button class="btn move" data-date="'+d.date+'" type="button">Change Date</button></div></td></tr>'}).join('')||'<tr><td colspan="6" class="muted">No saved reports yet.</td></tr>';custom()}
function custom(){let a=$('reportFrom').value,b=$('reportTo').value;if(!a||!b){$('customReport').innerHTML='';return}let rs=[];dateList(a,b).forEach(d=>(days[d]?.rows||[]).forEach(r=>rs.push(r)));let t=totals(rs),n=dateList(a,b).length,s=dateList(a,b).filter(d=>days[d]).length,top=Object.entries(t.p).sort((x,y)=>y[1]-x[1]).slice(0,8);$('customReport').innerHTML='<div class="report-summary"><div class="summary-box"><span>Total Sales</span><strong>'+money(t.sales)+'</strong></div><div class="summary-box"><span>Units Sold</span><strong>'+t.units+'</strong></div><div class="summary-box"><span>Stock Added</span><strong>'+t.added+'</strong></div><div class="summary-box"><span>Saved Days</span><strong>'+s+'/'+n+'</strong></div></div><div class="two-col"><div class="panel"><h3>Top Products</h3>'+(top.map(x=>'<div class="list-row"><span>'+esc(x[0])+'</span><b>'+money(x[1])+'</b></div>').join('')||'<p class="muted">No data.</p>')+'</div><div class="panel"><h3>Category Sales</h3>'+Object.entries(t.c).sort((x,y)=>y[1]-x[1]).map(x=>'<div class="list-row"><span>'+esc(x[0])+'</span><b>'+money(x[1])+'</b></div>').join('')+'</div></div>'}
function analytics(){let n=Number($('analyticsRange').value||7),ds=[];for(let i=n-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);ds.push(d.toLocaleDateString('en-CA'))}let v=ds.map(d=>({d,t:totals(days[d]?.rows||[])})),total=v.reduce((s,x)=>s+x.t.sales,0),units=v.reduce((s,x)=>s+x.t.units,0),best=[...v].sort((a,b)=>b.t.sales-a.t.sales)[0],max=Math.max(1,...v.map(x=>x.t.sales)),savedCount=v.filter(x=>x.t.sales||x.t.units||x.t.added||x.t.closing).length;$('aSales').textContent=money(total);$('aAvg').textContent=money(savedCount?total/savedCount:0);$('aUnits').textContent=units;$('aBest').textContent=best?.t.sales?best.d+' '+money(best.t.sales):'—';$('chart').innerHTML=v.map(x=>'<div class="bar-wrap" title="'+x.d+' — '+money(x.t.sales)+'"><div class="bar" style="height:'+Math.max(2,x.t.sales/max*210)+'px"></div><div class="bar-label">'+x.d.slice(5)+'</div></div>').join('');let p={},c={};v.forEach(x=>(days[x.d]?.rows||[]).forEach(r=>{let z=calc(r);p[r.name]=(p[r.name]||0)+z.sales;c[r.category]=(c[r.category]||0)+z.sales}));$('topProducts').innerHTML=Object.entries(p).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>'<div class="list-row"><span>'+esc(x[0])+'</span><b>'+money(x[1])+'</b></div>').join('')||'<p class="muted">No saved sales.</p>';$('catAnalytics').innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).map(x=>'<div class="list-row"><span>'+esc(x[0])+'</span><b>'+money(x[1])+'</b></div>').join('')||'<p class="muted">No saved sales.</p>'}
function csv(rs){return rs.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n')}function dl(n,t){let a=document.createElement('a'),u=URL.createObjectURL(new Blob([t],{type:'text/csv'}));a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
function save(){let d=$('businessDate').value||today();rows=rows.map(r=>({...r,closing:calc(r).closing}));let was=!!days[d]?.savedAt;days[d]={date:d,savedAt:days[d]?.savedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),rows:rows.map(r=>({...r}))};products=products.map(p=>{let r=rows.find(x=>x.id===p.id);return r?{...p,price:r.price}:p});dirty.d=true;dirty.p=true;if(!flush())return;toast(was?'Daily report updated':'Daily report saved');saveLabel();reports();analytics()}
function importX(){let f=$('excelFile').files[0];if(!f){toast('Select a file first');return}if(typeof XLSX==='undefined'&&!/\.csv$/i.test(f.name)){toast('Excel reader unavailable. Use CSV or refresh the page.');return}let rd=new FileReader();rd.onload=e=>{try{let data;if(typeof XLSX!=='undefined'){let w=XLSX.read(e.target.result,{type:'array'});data=XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{header:1,defval:''})}else{let text=new TextDecoder().decode(new Uint8Array(e.target.result));data=text.split(/\r?\n/).filter(Boolean).map(line=>line.split(',').map(x=>x.trim().replace(/^"|"$/g,'')))}if(data.length<2)throw Error('No product rows found');let h=data[0].map(x=>String(x).trim().toLowerCase().replace(/[_-]+/g,' ')),ix=(...ks)=>{for(const k of ks){const i=h.indexOf(k);if(i>=0)return i}return -1},ci=ix('category'),pi=ix('product','product name','item'),si=ix('sku','code','product code'),pr=ix('unit price','price','selling price'),oi=ix('opening stock','opening','stock');if([ci,pi,pr,oi].some(x=>x<0))throw Error('Required columns: Category, Product, Unit Price, Opening Stock');let count=0;data.slice(1).forEach(r=>{let name=String(r[pi]||'').trim();if(!name)return;let sku=String(si>=0?r[si]:'').trim(),p=(sku&&products.find(x=>x.id===sku))||products.find(x=>x.name.toLowerCase()===name.toLowerCase());if(p){p.category=normalize(r[ci]);p.name=name;p.price=num(r[pr]);p.opening=num(r[oi]);if(sku)p.id=sku}else products.push({id:sku||'P-'+Date.now()+'-'+count,category:normalize(r[ci]),name,price:num(r[pr]),opening:num(r[oi])});count++});write(S.p,products);prod();sales();$('importMessage').textContent=count+' product(s) imported successfully.';toast('Import complete')}catch(err){$('importMessage').textContent='Import failed: '+err.message}};rd.readAsArrayBuffer(f)}
function normalize(x){x=String(x||'').trim().toLowerCase();return x==='drink'||x==='drinks'?'Drinks':x==='snack'||x==='snacks'?'Snacks':x==='bread'?'Bread':x||'Other'}
function bind(){
$('businessDate').value=ui.date||today();$('reportFrom').value=ui.from||today();$('reportTo').value=ui.to||today();$('salesSearch').value=ui.search||'';
navigator.storage?.persist?.().catch(()=>{});
const leave=()=>flush();window.addEventListener('pagehide',leave);window.addEventListener('beforeunload',leave);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flush()});
window.addEventListener('storage',e=>{if(e.key!==S.d&&e.key!==S.p)return;let editing=document.activeElement?.matches?.('input,select');if(e.key===S.d){let v=read(S.d,{});if(v&&typeof v==='object'&&!Array.isArray(v))days=v}else{let v=read(S.p,null);if(Array.isArray(v))products=v}if(editing)return;let active=document.querySelector('.tab-section.active')?.id;if(active==='sales')sales();if(active==='products')prod();reports();analytics()});
document.addEventListener('click',e=>{let b=e.target.closest?.('.nav-btn');if(b){e.preventDefault();tab(b.dataset.tab);return}let o=e.target.closest?.('.open');if(o){e.preventDefault();flush();$('businessDate').value=o.dataset.date;ui.date=o.dataset.date;saveUI();tab('sales');return}let m=e.target.closest?.('.move');if(m){e.preventDefault();openMove(m.dataset.date)}});
$('salesBody')?.addEventListener('input',e=>{let i=e.target.closest('input[data-f]'),tr=i?.closest('tr');if(!i||!tr)return;let r=rows.find(x=>x.id===tr.dataset.id);if(!r)return;let f=i.dataset.f;if(f==='sold'){let av=calc(r).available;r.closing=av-Math.min(num(i.value),av)}else r[f]=num(i.value);refreshRow(tr,r,i);summary();persistDay()});
$('salesBody')?.addEventListener('click',e=>{let b=e.target.closest('.add-sale-btn');if(b)addSale(b.closest('tr'))});
$('salesBody')?.addEventListener('keydown',e=>{if(e.key!=='Enter'||e.isComposing||e.keyCode===229||!e.target.classList.contains('add-qty'))return;e.preventDefault();addSale(e.target.closest('tr'))});
$('changeDateBtn').addEventListener('click',()=>openMove($('businessDate').value||today()));
$('moveCancel').addEventListener('click',()=>$('moveDialog').close());
$('moveForm').addEventListener('submit',e=>{e.preventDefault();if(moveDay($('moveDialog').dataset.from,$('moveTo').value))$('moveDialog').close()});
$('salesSearch').addEventListener('input',()=>{ui.search=$('salesSearch').value;saveUI();sales()});$('businessDate').addEventListener('change',()=>{flush();ui.date=$('businessDate').value;saveUI();sales()});
$('reportFrom').addEventListener('change',()=>{ui.from=$('reportFrom').value;saveUI()});$('reportTo').addEventListener('change',()=>{ui.to=$('reportTo').value;saveUI()});
$('productsBody')?.addEventListener('input',e=>{let tr=e.target.closest('tr[data-pid]'),p=tr&&products.find(x=>x.id===tr.dataset.pid),f=e.target.dataset.f;if(!p||!f)return;p[f]=(f==='name'||f==='category')?e.target.value:num(e.target.value);persistProducts()});$('saveDayBtn').addEventListener('click',save);
$('productsBody')?.addEventListener('change',e=>{let tr=e.target.closest('tr[data-pid]'),p=tr&&products.find(x=>x.id===tr.dataset.pid),f=e.target.dataset.f;if(!p||!f)return;p[f]=(f==='name'||f==='category')?e.target.value:num(e.target.value);dirty.p=true;flush();sales();toast('Product updated')});
$('productsBody')?.addEventListener('click',e=>{if(!e.target.closest('.rm'))return;let id=e.target.closest('tr').dataset.pid;if(confirm('Remove this product?')){products=products.filter(x=>x.id!==id);write(S.p,products);prod();sales();}});
$('addProductBtn').addEventListener('click',()=>{let n=prompt('Product name:');if(!n?.trim())return;products.push({id:'P-'+Date.now(),category:normalize(prompt('Category:','Drinks')),name:n.trim(),price:num(prompt('Unit price:','0')),opening:num(prompt('Opening stock:','0'))});write(S.p,products);prod();sales();toast('Product added')});

$('generateReportBtn').addEventListener('click',custom);$('reportFrom').addEventListener('change',custom);$('reportTo').addEventListener('change',custom);$('analyticsRange').addEventListener('change',analytics);
$('exportCustomBtn').addEventListener('click',()=>{let a=$('reportFrom').value,b=$('reportTo').value,out=[['Date','Category','Product','Opening','Additions','Available','Closing','Sold','Unit Price','Sales']];dateList(a,b).forEach(d=>(days[d]?.rows||[]).forEach(r=>{let z=calc(r);out.push([d,r.category,r.name,r.opening,r.added,z.available,z.closing,z.sold,r.price,z.sales])}));dl('delite-cravings-report.csv',csv(out))});
$('exportAllBtn').addEventListener('click',()=>{let out=[['Date','Category','Product','Opening','Additions','Available','Closing','Sold','Unit Price','Sales']];Object.values(days).sort((a,b)=>a.date.localeCompare(b.date)).forEach(d=>(d.rows||[]).forEach(r=>{let z=calc(r);out.push([d.date,r.category,r.name,r.opening,r.added,z.available,z.closing,z.sold,r.price,z.sales])}));dl('delite-cravings-all-reports.csv',csv(out))});
$('importBtn').addEventListener('click',importX);$('downloadTemplateBtn').addEventListener('click',()=>dl('delite-cravings-stock-template.csv',csv([['Category','Product','SKU','Unit Price','Opening Stock'],['Drinks','Coke 50cl','DR-001',500,20],['Snacks','Meat Pie','SN-001',700,20],['Bread','Medium Bread','BR-001',1000,15]])));
$('logoutBtn').addEventListener('click',()=>{flush();sessionStorage.removeItem('dc_logged_in');location.reload()});
$('saveSettingsBtn').addEventListener('click',()=>{let u=$('newUser').value.trim(),p=$('newPin').value.trim(),c=$('confirmPin').value.trim();if(!u||!p)return $('settingsMessage').textContent='Username and PIN are required.';if(p!==c)return $('settingsMessage').textContent='PIN confirmation does not match.';write(S.a,{username:u,pin:p});$('settingsMessage').textContent='Login settings saved.';toast('Settings saved')});
$('resetDataBtn').addEventListener('click',()=>{if(!confirm('Reset products and reports?'))return;products=D.map(x=>({...x}));days={};write(S.p,products);write(S.d,days);prod();sales();reports();analytics();toast('Data reset')});
let a=auth();$('userDisplay').textContent='Signed in: '+a.username;$('newUser').value=a.username;prod();sales();reports();analytics();if(ui.tab&&ui.tab!=='sales')tab(ui.tab);status('All changes saved','saved');
}
function boot(){if(sessionStorage.getItem('dc_logged_in')==='1'){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');bind()}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
